/**
 * MHM SOLUTIONS — Après Mon Bac (MVP1)
 * Données de démonstration clairement étiquetées pour les programmes et domaines
 * Créateur : Hilarus GBAGOULE
 */

import { DemoProgramme, DomainSuggestion } from '../types/orientation';

export const DOMAIN_SUGGESTIONS: DomainSuggestion[] = [
  {
    id: 'informatique',
    name: 'Informatique & Intelligence Artificielle',
    iconName: 'Laptop',
    description: 'Développement logiciel, cybersécurité, science des données, cloud computing.',
    popularCareers: ['Ingénieur Logiciel', 'Data Analyst', 'Administrateur Systèmes', 'Expert Sécurité'],
  },
  {
    id: 'sante',
    name: 'Santé & Médecine',
    iconName: 'HeartPulse',
    description: 'Médecine générale, pharmacie, sciences infirmières, imagerie médicale.',
    popularCareers: ['Médecin', 'Pharmacien', 'Biologiste Médical', 'Sage-femme'],
  },
  {
    id: 'agriculture',
    name: 'Agriculture & Agroalimentaire',
    iconName: 'Sprout',
    description: 'Agrobusiness, production végétale, élevage, transformation alimentaire.',
    popularCareers: ['Ingénieur Agronome', 'Manager Agrobusiness', 'Contrôleur Qualité', 'Conseiller Agricole'],
  },
  {
    id: 'finance',
    name: 'Finance & Gestion',
    iconName: 'CircleDollarSign',
    description: 'Comptabilité, audit, banque, analyse financière, gestion de patrimoine.',
    popularCareers: ['Auditeur Financier', 'Analyste de Crédit', 'Contrôleur de Gestion', 'Comptable'],
  },
  {
    id: 'genie_civil',
    name: 'Génie Civil & BTP',
    iconName: 'HardHat',
    description: 'Construction d’infrastructures, routes, topographie, architecture.',
    popularCareers: ['Ingénieur BTP', 'Chef de Chantier', 'Géomètre Topographe', 'Calculateur de Structures'],
  },
  {
    id: 'environnement',
    name: 'Environnement & Énergies Renouvelables',
    iconName: 'Trees',
    description: 'Gestion des ressources naturelles, transition écologique, climat, énergies solaires.',
    popularCareers: ['Expert Climat', 'Ingénieur Solaire', 'Gestionnaire d’Espaces Protégés', 'Écologue'],
  },
  {
    id: 'commerce',
    name: 'Commerce & Marketing Digital',
    iconName: 'ShoppingBag',
    description: 'Négociation commerciale, e-commerce, stratégie de marque, communication d’entreprise.',
    popularCareers: ['Responsable Commercial', 'Digital Marketer', 'Chef de Produit', 'Growth Manager'],
  },
  {
    id: 'administration',
    name: 'Administration & Droit',
    iconName: 'Scale',
    description: 'Droit public et privé, administration territoriale, diplomatie, ressources humaines.',
    popularCareers: ['Juriste d’Entreprise', 'Attaché d’Administration', 'Magistrat', 'Consultant RH'],
  },
  {
    id: 'enseignement',
    name: 'Enseignement & Recherche',
    iconName: 'GraduationCap',
    description: 'Pédagogie, formation des formateurs, recherche scientifique fondamentale et appliquée.',
    popularCareers: ['Professeur Certifié', 'Chercheur', 'Concepteur Pédagogique', 'Inspecteur de l’Éducation'],
  },
  {
    id: 'communication',
    name: 'Communication & Médias',
    iconName: 'Megaphone',
    description: 'Journalisme, relations publiques, production audiovisuelle, création de contenu.',
    popularCareers: ['Journaliste', 'Attaché de Presse', 'Community Manager', 'Producteur Multimédia'],
  },
];

export const DEMO_PROGRAMMES: DemoProgramme[] = [
  {
    id: 'prog-01',
    university: 'Université d’Abomey-Calavi (UAC)',
    school: 'IFRI (Institut de Formation et de Recherche en Informatique)',
    programme: 'Génie Logiciel & Systèmes d’Information',
    domain: 'Informatique & Intelligence Artificielle',
    description: 'Formation d’élite pour concevoir et déployer des architectures logicielles modernes, applications web/mobiles et bases de données robustes.',
    admissibleSeries: ['C', 'D', 'E', 'B'],
    is_demo: true,
    demoStats: {
      estimatedCapacity: 120,
      estimatedScholarships: 55,
      scholarshipRatio: 0.46,
      competitionLevel: 'Élevé',
      competitionScore: 8,
      employmentRateDemo: 92,
      marketDemand: 'Forte',
      keySubjects: ['Mathématiques', 'Algorithmique', 'Logique'],
      sampleCareers: ['Développeur Full-Stack', 'Architecte Logiciel', 'Ingénieur DevOps'],
    },
  },
  {
    id: 'prog-02',
    university: 'Université Nationale d’Agriculture (UNA)',
    school: 'EAC (École d’Agrobusiness et de Politiques Agricoles)',
    programme: 'Agrobusiness & Économie Rurale',
    domain: 'Agriculture & Agroalimentaire',
    description: 'Spécialisation en gestion d’exploitations modernes, chaînes de valeur agricoles, finance rurale et entrepreneuriat vert.',
    admissibleSeries: ['D', 'C', 'B', 'A'],
    is_demo: true,
    demoStats: {
      estimatedCapacity: 90,
      estimatedScholarships: 60,
      scholarshipRatio: 0.67,
      competitionLevel: 'Modéré',
      competitionScore: 5,
      employmentRateDemo: 88,
      marketDemand: 'Forte',
      keySubjects: ['SVT', 'Économie', 'Statistiques'],
      sampleCareers: ['Manager d’Entreprise Agricole', 'Analyste Chaîne de Valeur', 'Chef de Projet Rural'],
    },
  },
  {
    id: 'prog-03',
    university: 'Université d’Abomey-Calavi (UAC)',
    school: 'EPAC (École Polytechnique d’Abomey-Calavi)',
    programme: 'Génie Civil & Bâtiment',
    domain: 'Génie Civil & BTP',
    description: 'Étude des structures, calcul des ponts et chaussées, résistance des matériaux et gestion de chantiers d’infrastructures.',
    admissibleSeries: ['C', 'D', 'E'],
    is_demo: true,
    demoStats: {
      estimatedCapacity: 75,
      estimatedScholarships: 32,
      scholarshipRatio: 0.43,
      competitionLevel: 'Très élevé',
      competitionScore: 9,
      employmentRateDemo: 89,
      marketDemand: 'Forte',
      keySubjects: ['Physique-Chimie', 'Mathématiques', 'Mécanique'],
      sampleCareers: ['Ingénieur Travaux', 'Chef de Projet BTP', 'Expert Contrôle Technique'],
    },
  },
  {
    id: 'prog-04',
    university: 'Université de Parakou (UP)',
    school: 'IUT (Institut Universitaire de Technologie)',
    programme: 'Banque, Finance & Assurances',
    domain: 'Finance & Gestion',
    description: 'Techniques bancaires, analyse financière des entreprises, gestion des risques et microfinance adaptée au contexte régional.',
    admissibleSeries: ['B', 'C', 'D', 'Autre'],
    is_demo: true,
    demoStats: {
      estimatedCapacity: 110,
      estimatedScholarships: 50,
      scholarshipRatio: 0.45,
      competitionLevel: 'Modéré',
      competitionScore: 6,
      employmentRateDemo: 84,
      marketDemand: 'Moyenne',
      keySubjects: ['Mathématiques Financières', 'Comptabilité', 'Économie'],
      sampleCareers: ['Gestionnaire de Portefeuille', 'Chargé de Clientèle', 'Analyste Crédit'],
    },
  },
  {
    id: 'prog-05',
    university: 'Université d’Abomey-Calavi (UAC)',
    school: 'FSS (Faculté des Sciences de la Santé)',
    programme: 'Médecine Générale',
    domain: 'Santé & Médecine',
    description: 'Cycle complet d’études médicales préparant aux diagnostics cliniques, thérapeutiques, chirurgie de base et santé publique.',
    admissibleSeries: ['C', 'D'],
    is_demo: true,
    demoStats: {
      estimatedCapacity: 150,
      estimatedScholarships: 45,
      scholarshipRatio: 0.30,
      competitionLevel: 'Très élevé',
      competitionScore: 10,
      employmentRateDemo: 98,
      marketDemand: 'Forte',
      keySubjects: ['SVT / Biologie', 'Physique-Chimie', 'Mathématiques'],
      sampleCareers: ['Médecin Généraliste', 'Médecin Urgentiste', 'Épidémiologiste'],
    },
  },
  {
    id: 'prog-06',
    university: 'Université Nationale d’Agriculture (UNA)',
    school: 'ESA (École des Sciences Agronomiques)',
    programme: 'Production Végétale & Protection des Cultures',
    domain: 'Agriculture & Agroalimentaire',
    description: 'Amélioration des rendements agricoles, biotechnologies végétales, gestion intégrée des ravageurs et semences certifiées.',
    admissibleSeries: ['D', 'C'],
    is_demo: true,
    demoStats: {
      estimatedCapacity: 80,
      estimatedScholarships: 58,
      scholarshipRatio: 0.72,
      competitionLevel: 'Faible',
      competitionScore: 4,
      employmentRateDemo: 86,
      marketDemand: 'Forte',
      keySubjects: ['Biologie Végétale', 'Chimie des Sols', 'Agronomie'],
      sampleCareers: ['Spécialiste Phytosanitaire', 'Sélectionneur Végétal', 'Consultant Semencier'],
    },
  },
  {
    id: 'prog-07',
    university: 'Université Nationale des Sciences (UNSTIM)',
    school: 'ENS (École Normale Supérieure de Natitingou)',
    programme: 'Sciences Physiques & Enseignement',
    domain: 'Enseignement & Recherche',
    description: 'Formation pédagogique et scientifique pour les futurs professeurs du secondaire en physique et chimie.',
    admissibleSeries: ['C', 'D', 'E'],
    is_demo: true,
    demoStats: {
      estimatedCapacity: 60,
      estimatedScholarships: 48,
      scholarshipRatio: 0.80,
      competitionLevel: 'Modéré',
      competitionScore: 5,
      employmentRateDemo: 95,
      marketDemand: 'Forte',
      keySubjects: ['Physique', 'Chimie', 'Pédagogie'],
      sampleCareers: ['Professeur de Lycée', 'Formateur', 'Conseiller Pédagogique'],
    },
  },
  {
    id: 'prog-08',
    university: 'Université d’Abomey-Calavi (UAC)',
    school: 'FADESP (Faculté de Droit et de Science Politique)',
    programme: 'Droit Public & Administration des Collectivités',
    domain: 'Administration & Droit',
    description: 'Droit constitutionnel, contentieux administratif, gouvernance locale, marchés publics et décentralisation.',
    admissibleSeries: ['A', 'B', 'D', 'C'],
    is_demo: true,
    demoStats: {
      estimatedCapacity: 300,
      estimatedScholarships: 80,
      scholarshipRatio: 0.27,
      competitionLevel: 'Élevé',
      competitionScore: 7,
      employmentRateDemo: 79,
      marketDemand: 'Moyenne',
      keySubjects: ['Français / Expression', 'Histoire-Géo', 'Philosophie'],
      sampleCareers: ['Attaché d’Administration', 'Juriste Territorial', 'Conseiller Juridique'],
    },
  },
  {
    id: 'prog-09',
    university: 'Université de Parakou (UP)',
    school: 'FA (Faculté d’Agronomie)',
    programme: 'Foresterie & Écogestion des Ressources Naturelles',
    domain: 'Environnement & Énergies Renouvelables',
    description: 'Protection de la biodiversité, aménagement forestier durable, séquestration carbone et écologie tropicale.',
    admissibleSeries: ['D', 'C', 'A'],
    is_demo: true,
    demoStats: {
      estimatedCapacity: 70,
      estimatedScholarships: 45,
      scholarshipRatio: 0.64,
      competitionLevel: 'Faible',
      competitionScore: 3,
      employmentRateDemo: 82,
      marketDemand: 'Émergente',
      keySubjects: ['SVT', 'Écologie', 'Géographie'],
      sampleCareers: ['Conservateur de Parc', 'Chargé d’Études Environnement', 'Expert Carbone'],
    },
  },
  {
    id: 'prog-10',
    university: 'Université d’Abomey-Calavi (UAC)',
    school: 'ENAM (École Nationale d’Administration et de Magistrature)',
    programme: 'Administration Générale & Territoriale',
    domain: 'Administration & Droit',
    description: 'Formation des cadres de l’État, gestion publique, éthique républicaine et politiques de développement.',
    admissibleSeries: ['A', 'B', 'C', 'D'],
    is_demo: true,
    demoStats: {
      estimatedCapacity: 60,
      estimatedScholarships: 30,
      scholarshipRatio: 0.50,
      competitionLevel: 'Très élevé',
      competitionScore: 9,
      employmentRateDemo: 96,
      marketDemand: 'Forte',
      keySubjects: ['Culture Générale', 'Droit Administratif', 'Économie'],
      sampleCareers: ['Administrateur Civil', 'Secrétaire Général de Mairie', 'Cadre de Ministère'],
    },
  },
];
