import React, { useEffect, useState } from 'react';
import { Award, ExternalLink, FlaskConical, Globe2, Linkedin, ShieldCheck, Sparkles, UsersRound } from 'lucide-react';
import { listPublicBetaContributors, type PublicBetaContributor } from '../lib/betaContributors';

export const BetaContributorsPage: React.FC<{ navigate: (route: string) => void }> = ({ navigate }) => {
  const [contributors, setContributors] = useState<PublicBetaContributor[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    void listPublicBetaContributors()
      .then(setContributors)
      .catch(() => setContributors([]))
      .finally(() => setLoading(false));
  }, []);

  return <section className="bg-slate-50 py-12 dark:bg-slate-950 sm:py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><header className="mx-auto max-w-3xl text-center"><div className="inline-flex items-center gap-2 rounded-full border border-rose-200 bg-rose-50 px-3 py-1.5 text-xs font-black uppercase tracking-[0.16em] text-rose-600 dark:border-rose-900/50 dark:bg-rose-950/20 dark:text-rose-300"><UsersRound className="h-3.5 w-3.5" /> Communauté BacPilot</div><h1 className="mt-5 text-4xl font-black tracking-tight text-slate-950 dark:text-white sm:text-5xl">Les contributeurs bêta qui font avancer BacPilot.</h1><p className="mt-5 text-base leading-8 text-slate-600 dark:text-slate-300">BacPilot évolue grâce à des volontaires qui testent les parcours, signalent ce qui bloque et partagent des améliorations utiles. Cette page ne présente que les personnes ayant choisi d’être reconnues publiquement.</p></header>

    <div className="mt-10 grid gap-4 md:grid-cols-3"><Principle icon={<ShieldCheck className="h-5 w-5" />} title="Une visibilité choisie" text="Chaque membre décide de son nom public, de ses liens, de sa photo et de l’indexation éventuelle de son profil." /><Principle icon={<Award className="h-5 w-5" />} title="Une contribution explicable" text="L’indice repose sur des tests et retours réellement enregistrés, puis étudiés ou résolus par l’équipe." /><Principle icon={<Sparkles className="h-5 w-5" />} title="Une amélioration continue" text="Les retours contribuent à rendre l’expérience plus claire, plus robuste et plus utile aux futurs bacheliers." /></div>

    <div className="mt-14 flex flex-col items-start justify-between gap-4 border-b border-slate-200 pb-5 dark:border-slate-800 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-rose-500">Reconnaissance publique</p><h2 className="mt-2 text-2xl font-black">Profils contributeurs</h2></div><button type="button" onClick={() => navigate('/beta')} className="inline-flex items-center gap-2 rounded-xl bg-rose-500 px-5 py-3 text-sm font-black text-white hover:bg-rose-600"><FlaskConical className="h-4 w-4" /> Je suis bêta-testeur</button></div>

    {loading ? <div className="grid gap-5 py-8 sm:grid-cols-2 lg:grid-cols-3">{[1, 2, 3].map((item) => <div key={item} className="h-64 animate-pulse rounded-3xl bg-slate-200 dark:bg-slate-800" />)}</div> : contributors.length ? <div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{contributors.map((contributor) => <ContributorCard key={`${contributor.public_name}-${contributor.portfolio_url || contributor.linkedin_url || contributor.contribution_score}`} contributor={contributor} />)}</div> : <div className="mt-8 rounded-3xl border border-dashed border-slate-300 bg-white p-8 text-center dark:border-slate-700 dark:bg-slate-900"><Globe2 className="mx-auto h-8 w-8 text-rose-500" /><h3 className="mt-4 text-xl font-black">La reconnaissance commence avec les premiers volontaires.</h3><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-slate-500">Les profils apparaîtront ici lorsque leurs auteurs auront choisi de les publier. Les contributions privées restent privées.</p><button type="button" onClick={() => navigate('/beta')} className="mt-6 rounded-xl border border-slate-300 px-5 py-3 text-sm font-bold dark:border-slate-700">Découvrir l’espace bêta</button></div>}

    <div className="mt-14 rounded-3xl bg-slate-950 p-7 text-white sm:p-10"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.16em] text-rose-300">Vous participez déjà ?</p><h2 className="mt-3 text-3xl font-black">Votre contribution mérite d’être reconnue, selon vos propres choix.</h2><p className="mt-4 leading-7 text-slate-300">Depuis votre espace bêta, suivez votre indice de contribution, choisissez votre niveau de visibilité et créez un profil public seulement si vous le souhaitez.</p><button type="button" onClick={() => navigate('/beta')} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 font-black text-slate-950"><Award className="h-4 w-4" /> Gérer mon profil contributeur</button></div></div>
  </div></section>;
};

const Principle: React.FC<{ icon: React.ReactNode; title: string; text: string }> = ({ icon, title, text }) => <div className="rounded-3xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><div className="inline-flex rounded-2xl bg-rose-50 p-3 text-rose-500 dark:bg-rose-950/30">{icon}</div><h2 className="mt-4 font-black">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>;

const ContributorCard: React.FC<{ contributor: PublicBetaContributor }> = ({ contributor }) => {
  const profileHref = contributor.publication_status === 'published_profile' && contributor.public_slug ? `/contributeurs-beta/${contributor.public_slug}` : null;
  return <article className="overflow-hidden rounded-3xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-4 bg-slate-950 p-6 text-white"><div className="flex h-16 w-16 shrink-0 items-center justify-center overflow-hidden rounded-2xl bg-gradient-to-br from-rose-400 to-fuchsia-600 text-xl font-black">{contributor.photo_url ? <img src={contributor.photo_url} alt={`Photo de ${contributor.public_name}`} className="h-full w-full object-cover" /> : contributor.public_name.slice(0, 1).toLocaleUpperCase()}</div><div className="min-w-0"><h3 className="truncate text-lg font-black">{contributor.public_name}</h3><p className="mt-1 text-sm text-rose-200">{contributor.contribution_level}</p></div></div><div className="p-6"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.12em] text-slate-400">Indice de contribution</p><p className="mt-1 text-3xl font-black text-rose-500">{contributor.contribution_score}<span className="text-base text-slate-400">/100</span></p></div><Award className="h-6 w-6 text-amber-500" /></div>{contributor.public_bio && <p className="mt-5 text-sm leading-6 text-slate-600 dark:text-slate-300">{contributor.public_bio}</p>}{contributor.focus_areas.length > 0 && <div className="mt-5 flex flex-wrap gap-2">{contributor.focus_areas.map((area) => <span key={area} className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600 dark:bg-slate-800 dark:text-slate-300">{area}</span>)}</div>}{(contributor.portfolio_url || contributor.linkedin_url) && <div className="mt-6 flex flex-wrap gap-3">{contributor.portfolio_url && <a href={contributor.portfolio_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-sm font-bold text-rose-600 hover:underline"><ExternalLink className="h-3.5 w-3.5" /> Portfolio</a>}{contributor.linkedin_url && <a href={contributor.linkedin_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-sm font-bold text-sky-600 hover:underline"><Linkedin className="h-3.5 w-3.5" /> LinkedIn</a>}</div>}{profileHref && <a href={profileHref} className="mt-6 inline-flex items-center gap-2 text-sm font-black text-rose-600 hover:underline"><ExternalLink className="h-3.5 w-3.5" /> Voir la fiche publique</a>}</div></article>;
};

export default BetaContributorsPage;
