import React from 'react';
import { ArrowRight, Radio, Sparkles } from 'lucide-react';
import { formatFreshness, useLiveProgrammes } from '../lib/liveProgrammes';

interface HomePageProps { navigate: (route: string) => void; }

export const HomePage: React.FC<HomePageProps> = ({ navigate }) => {
  const live = useLiveProgrammes(9);
  return <main className="bg-slate-50 text-slate-900 dark:bg-slate-950 dark:text-white">
    <section className="border-b border-slate-800 bg-slate-950 px-4 py-20 text-white sm:py-28"><div className="mx-auto max-w-4xl text-center"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-rose-300">BacPilot · par MHM SOLUTIONS</p><h1 className="mt-6 text-4xl font-bold tracking-tight sm:text-6xl">Comprendre tes possibilités avant de choisir.</h1><p className="mx-auto mt-6 max-w-2xl text-base leading-relaxed text-slate-300 sm:text-lg">Nous centralisons les relevés observés pendant la campagne d’orientation pour t’aider à comparer les filières selon ton objectif. Les données sont affichées telles qu’elles sont reçues, sans promesse d’admission.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><button onClick={() => navigate('/onboarding')} className="inline-flex items-center justify-center gap-2 rounded-xl bg-rose-500 px-6 py-3 font-bold">Parler à BacPilot <ArrowRight className="h-4 w-4" /></button><button onClick={() => document.getElementById('live-data')?.scrollIntoView({ behavior: 'smooth' })} className="rounded-xl border border-slate-700 px-6 py-3 font-semibold text-slate-200">Voir les données observées</button></div><p className="mt-8 text-xs text-slate-500">Initiative fondée par Hilarus GBAGOULE · MHM SOLUTIONS</p></div></section>
    <section className="mx-auto max-w-6xl px-4 py-14"><div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><p className="text-xs font-semibold uppercase text-rose-500">1</p><h2 className="mt-2 font-bold">Tu renseignes tes informations</h2><p className="mt-2 text-sm text-slate-500">Une conversation guidée : nom, série, mention, objectif et domaine.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><p className="text-xs font-semibold uppercase text-rose-500">2</p><h2 className="mt-2 font-bold">BacPilot analyse les observations</h2><p className="mt-2 text-sm text-slate-500">Il vérifie la fraîcheur des données et explique les trois pistes calculées selon ton objectif.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><p className="text-xs font-semibold uppercase text-rose-500">3</p><h2 className="mt-2 font-bold">Tu gardes le dernier mot</h2><p className="mt-2 text-sm text-slate-500">Les propositions viennent des relevés reçus. La vérification et la validation finale restent les tiennes.</p></div></div></section>
    <section id="live-data" className="mx-auto max-w-6xl px-4 pb-16"><div className="mb-6 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-wider text-emerald-600">Données publiques observées</p><h2 className="mt-2 text-3xl font-bold">Ce qui est mesuré maintenant</h2><p className="mt-2 text-sm text-slate-500">Dernière collecte : {formatFreshness(live.lastUpdated)}</p></div><div className="inline-flex items-center gap-2 text-xs font-semibold text-emerald-600"><Radio className="h-4 w-4" />{live.realtime === 'connected' ? 'Temps réel connecté' : 'Connexion en cours'}</div></div>{live.loading && <div className="rounded-2xl bg-white p-8 text-center text-sm text-slate-500 dark:bg-slate-900">Chargement des relevés…</div>}{!live.loading && live.rows.length === 0 && <div className="rounded-2xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500 dark:border-slate-700">Aucun relevé réel pour le moment. La collecte se fait depuis l’extension.</div>}<div className="grid gap-4 md:grid-cols-3">{live.rows.map((row) => <article key={row.programme_id} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><p className="text-xs text-slate-400">{row.university} · {row.school}</p><h3 className="mt-2 font-bold">{row.programme}</h3><div className="mt-4 flex items-end justify-between"><div><strong className="text-3xl text-rose-500">{row.score_opportunity ?? '—'}</strong><span className="ml-1 text-xs text-slate-400">/100</span></div><div className="text-right text-xs text-slate-500">{row.scholarships} bourses<br />{row.total} inscrits</div></div></article>)}</div></section>
    <section className="border-t border-slate-200 bg-white px-4 py-12 dark:border-slate-800 dark:bg-slate-900"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-5 sm:flex-row sm:items-center"><div className="flex gap-3"><Sparkles className="mt-1 h-5 w-5 text-indigo-500" /><div><h2 className="font-bold">Un assistant transparent, puis un guide officiel</h2><p className="mt-1 max-w-2xl text-sm text-slate-500">BacPilot explique déjà les scores fondés sur les observations synchronisées. La prochaine évolution intégrera des extraits sourcés du guide officiel et des débouchés, sans transformer une suggestion en garantie.</p></div></div><button onClick={() => navigate('/onboarding')} className="inline-flex items-center gap-2 self-start rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold dark:border-slate-700">Commencer <ArrowRight className="h-4 w-4" /></button></div></section>
  </main>;
};
export default HomePage;
