import React, { useState } from 'react';
import { LayoutDashboard, User, Info, LogOut, LogIn, UserPlus, Menu, X, BookOpen, FlaskConical, Gift } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

interface NavbarProps { currentRoute: string; navigate: (route: string) => void; openTestsModal?: () => void; }

export const Navbar: React.FC<NavbarProps> = ({ currentRoute, navigate }) => {
  const { user, profile, isBetaTester, signOut } = useAuth();
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const go = (route: string) => { navigate(route); setMobileMenuOpen(false); };
  const onInternalLink = (event: React.MouseEvent<HTMLAnchorElement>, route: string) => {
    if (event.metaKey || event.ctrlKey || event.shiftKey || event.altKey || event.button !== 0) return;
    event.preventDefault();
    go(route);
  };
  const active = (route: string) => currentRoute === route ? 'bg-slate-800 text-white' : 'text-slate-300 hover:bg-slate-800/60 hover:text-white';

  return <header className="sticky top-0 z-40 border-b border-slate-800 bg-slate-950/95 text-white backdrop-blur-md"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex h-16 items-center justify-between sm:h-20">
    <a href="/" onClick={(event) => onInternalLink(event, '/')} className="flex items-center gap-3 text-left"><span className="flex h-10 w-10 items-center justify-center"><img src="/branding/bacpilot-mark-512.png" alt="Logo BacPilot" className="h-10 w-auto shrink-0 object-contain" /></span><span><strong className="block text-lg tracking-tight">Bac<span className="text-rose-400">Pilot</span></strong><small className="text-xs text-slate-400">par MHM SOLUTIONS</small></span></a>
    <nav className="hidden items-center gap-1 md:flex" aria-label="Navigation principale"><a href="/" onClick={(event) => onInternalLink(event, '/')} className={`rounded-lg px-3 py-2 text-sm font-medium ${active('/')}`}>Accueil</a><a href="/orientation-bac-benin" onClick={(event) => onInternalLink(event, '/orientation-bac-benin')} className={`flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-medium ${active('/orientation-bac-benin')}`}><BookOpen className="h-4 w-4" /> Guide orientation</a><a href="/methodologie" onClick={(event) => onInternalLink(event, '/methodologie')} className={`rounded-lg px-3 py-2 text-sm font-medium ${active('/methodologie')}`}>Méthode</a><button onClick={() => go('/parrainage')} className={`flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-semibold ${active('/parrainage')} text-rose-200`}><Gift className="h-4 w-4" /> Parrainer</button><a href="/about" onClick={(event) => onInternalLink(event, '/about')} className={`flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-medium ${active('/about')}`}><Info className="h-4 w-4" /> À propos</a><a href="https://partenaires.bacpilot.site" className="rounded-lg px-3 py-2 text-sm font-medium text-slate-300 hover:bg-slate-800/60 hover:text-white">Partenaires</a>{user && <><button onClick={() => go('/dashboard')} className={`flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-medium ${active('/dashboard')}`}><LayoutDashboard className="h-4 w-4" /> Tableau de bord</button><button onClick={() => go('/profile')} className={`flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-medium ${active('/profile')}`}><User className="h-4 w-4" /> Mon profil</button>{isBetaTester && <button onClick={() => go('/beta')} className={`flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-bold ${active('/beta')} text-rose-300`}><FlaskConical className="h-4 w-4" /> Espace bêta</button>}</>}</nav>
    <div className="hidden items-center gap-2 md:flex">{user ? <><span className="max-w-32 truncate text-sm text-slate-300">{profile?.display_name || 'Mon espace'}</span><button onClick={async () => { await signOut(); go('/'); }} title="Se déconnecter" className="rounded-lg p-2 text-slate-400 hover:bg-slate-800 hover:text-rose-400"><LogOut className="h-5 w-5" /></button></> : <><button onClick={() => go('/login')} className="flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-medium text-slate-300 hover:bg-slate-800"><LogIn className="h-4 w-4" /> Connexion</button><button onClick={() => go('/register')} className="flex items-center gap-1.5 rounded-lg bg-rose-500 px-4 py-2 text-sm font-semibold text-white"><UserPlus className="h-4 w-4" /> Créer mon profil</button></>}</div>
    <button onClick={() => setMobileMenuOpen((open) => !open)} className="rounded-lg p-2 text-slate-300 hover:bg-slate-800 md:hidden" aria-label="Ouvrir le menu" aria-expanded={mobileMenuOpen}>{mobileMenuOpen ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}</button>
  </div></div>{mobileMenuOpen && <div className="space-y-2 border-t border-slate-800 bg-slate-950 px-4 py-4 md:hidden"><a href="/" onClick={(event) => onInternalLink(event, '/')} className={`block w-full rounded-lg px-3 py-2 text-left text-sm ${active('/')}`}>Accueil</a><a href="/orientation-bac-benin" onClick={(event) => onInternalLink(event, '/orientation-bac-benin')} className={`block w-full rounded-lg px-3 py-2 text-left text-sm ${active('/orientation-bac-benin')}`}>Guide orientation</a><a href="/methodologie" onClick={(event) => onInternalLink(event, '/methodologie')} className={`block w-full rounded-lg px-3 py-2 text-left text-sm ${active('/methodologie')}`}>Méthode</a><button onClick={() => go('/parrainage')} className={`flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm font-semibold ${active('/parrainage')} text-rose-200`}><Gift className="h-4 w-4" /> Parrainer</button><a href="/about" onClick={(event) => onInternalLink(event, '/about')} className={`block w-full rounded-lg px-3 py-2 text-left text-sm ${active('/about')}`}>À propos</a><a href="https://partenaires.bacpilot.site" className="block w-full rounded-lg px-3 py-2 text-left text-sm text-slate-300 hover:bg-slate-800/60 hover:text-white">Devenir partenaire</a>{user ? <><button onClick={() => go('/dashboard')} className={`block w-full rounded-lg px-3 py-2 text-left text-sm ${active('/dashboard')}`}>Tableau de bord</button><button onClick={() => go('/profile')} className={`block w-full rounded-lg px-3 py-2 text-left text-sm ${active('/profile')}`}>Mon profil</button>{isBetaTester && <button onClick={() => go('/beta')} className={`flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm text-rose-300 ${active('/beta')}`}><FlaskConical className="h-4 w-4" /> Espace bêta</button>}<button onClick={() => go('/onboarding')} className="block w-full rounded-lg px-3 py-2 text-left text-sm text-rose-300">Modifier mon parcours</button></> : <><button onClick={() => go('/login')} className="block w-full rounded-lg px-3 py-2 text-left text-sm text-slate-300">Connexion</button><button onClick={() => go('/register')} className="block w-full rounded-lg bg-rose-500 px-3 py-2 text-left text-sm font-semibold">Créer mon profil</button></>}</div>}</header>;
};

export default Navbar;
