import React, { useState } from 'react';
import { LayoutDashboard, User, Info, LogOut, LogIn, UserPlus, Menu, X } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

interface NavbarProps { currentRoute: string; navigate: (route: string) => void; openTestsModal?: () => void; }

export const Navbar: React.FC<NavbarProps> = ({ currentRoute, navigate }) => {
  const { user, profile, signOut } = useAuth();
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const go = (route: string) => { navigate(route); setMobileMenuOpen(false); };
  const active = (route: string) => currentRoute === route ? 'bg-slate-800 text-white' : 'text-slate-300 hover:bg-slate-800/60 hover:text-white';
  return <header className="sticky top-0 z-40 border-b border-slate-800 bg-slate-950/95 text-white backdrop-blur-md"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex h-16 items-center justify-between sm:h-20">
    <button onClick={() => go('/')} className="flex items-center gap-3 text-left"><span className="flex h-10 w-10 items-center justify-center overflow-hidden rounded-xl bg-rose-500"><img src="/branding/bacpilot-mark-final.png" alt="" className="h-9 w-9 object-contain" /></span><span><strong className="block text-lg tracking-tight">Bac<span className="text-rose-400">Pilot</span></strong><small className="text-xs text-slate-400">par MHM SOLUTIONS</small></span></button>
    <nav className="hidden items-center gap-1 md:flex"><button onClick={() => go('/')} className={`rounded-lg px-3 py-2 text-sm font-medium ${active('/')}`}>Accueil</button><button onClick={() => go('/about')} className={`flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-medium ${active('/about')}`}><Info className="h-4 w-4" /> À propos</button>{user && <><button onClick={() => go('/dashboard')} className={`flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-medium ${active('/dashboard')}`}><LayoutDashboard className="h-4 w-4" /> Tableau de bord</button><button onClick={() => go('/profile')} className={`flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-medium ${active('/profile')}`}><User className="h-4 w-4" /> Mon profil</button></>}</nav>
    <div className="hidden items-center gap-2 md:flex">{user ? <><span className="max-w-32 truncate text-sm text-slate-300">{profile?.display_name || 'Mon espace'}</span><button onClick={async () => { await signOut(); go('/'); }} title="Se déconnecter" className="rounded-lg p-2 text-slate-400 hover:bg-slate-800 hover:text-rose-400"><LogOut className="h-5 w-5" /></button></> : <><button onClick={() => go('/login')} className="flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-medium text-slate-300 hover:bg-slate-800"><LogIn className="h-4 w-4" /> Connexion</button><button onClick={() => go('/register')} className="flex items-center gap-1.5 rounded-lg bg-rose-500 px-4 py-2 text-sm font-semibold text-white"><UserPlus className="h-4 w-4" /> Créer mon profil</button></>}</div>
    <button onClick={() => setMobileMenuOpen((open) => !open)} className="rounded-lg p-2 text-slate-300 hover:bg-slate-800 md:hidden" aria-label="Ouvrir le menu">{mobileMenuOpen ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}</button>
  </div></div>{mobileMenuOpen && <div className="space-y-2 border-t border-slate-800 bg-slate-950 px-4 py-4 md:hidden"><button onClick={() => go('/')} className={`block w-full rounded-lg px-3 py-2 text-left text-sm ${active('/')}`}>Accueil</button><button onClick={() => go('/about')} className={`block w-full rounded-lg px-3 py-2 text-left text-sm ${active('/about')}`}>À propos</button>{user ? <><button onClick={() => go('/dashboard')} className={`block w-full rounded-lg px-3 py-2 text-left text-sm ${active('/dashboard')}`}>Tableau de bord</button><button onClick={() => go('/profile')} className={`block w-full rounded-lg px-3 py-2 text-left text-sm ${active('/profile')}`}>Mon profil</button><button onClick={() => go('/onboarding')} className="block w-full rounded-lg px-3 py-2 text-left text-sm text-rose-300">Modifier mon parcours</button></> : <><button onClick={() => go('/login')} className="block w-full rounded-lg px-3 py-2 text-left text-sm text-slate-300">Connexion</button><button onClick={() => go('/register')} className="block w-full rounded-lg bg-rose-500 px-3 py-2 text-left text-sm font-semibold">Créer mon profil</button></>}</div>}</header>;
};
export default Navbar;
